name: roquiz
description: |
  Applicazione per esercitarsi con i quiz di Ricerca Operativa M.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0-beta+0

environment:
  sdk: ^3.8.1
  flutter: ^3.32.5

# Check updates with: `flutter pub outdated`
# Update with: `flutter pub upgrade --major-versions`
dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  provider: ^6.1.2
  yaml: ^3.1.3
  url_launcher: ^6.3.2
  confetti: ^0.8.0
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules in analysis_options.yaml
  flutter_lints: ^5.0.0
  test: ^1.25.8
  json_serializable: ^6.10.0
  build_runner: ^2.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/licenses.json
    - assets/domande.txt
    - assets/questions.yaml
    - assets/credits.json
    - assets/contributors/contributors.yaml
    - assets/contributors/avatars/
