name: roquiz
description: "Applicazione per esercitarsi con i quiz di Ricerca Operativa M."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.11.3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true

  assets:
    - assets/licenses.json
    - assets/domande.txt
    - assets/credits.json
    - assets/icons/logo.svg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
