name: Flutter CI/CD

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - 'releases/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./roquiz
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ./roquiz/pubspec.yaml

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test test/example.dart
